### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#10]
remove the legacy code in branch 'hao'

**Comment by klauszhang** [comment]
hey, when I was doing the 'removing legacy code' i think parts of the codes are still useful. I put them here for you to decide whether to remove them:

# all the legacy codes within `hao`  branch

* `app/controllers/search_controller.rb`:
 * `index method` full text search, display the search result (in EvidenceItem) via `app/views/search/index.html.erb`
 * `app/views/layouts/search.html.erb` basic layout file for all views in `app/views/search`
 * `app/assets/stylesheets/search.css.scss` and related scss files - style sheets for search views.
*`app/controllers/pages_controller.rb`:
 * the content in index method (`@item=EvidenceItem.all
`) can be discard, it is used to display all the content in `EvidenceItem` 
 * `app/views/pages/index.html.erb`  -  the view with search box
 * `app/assets/stylesheets/pages.css.scss` and related scss files - style sheets for pages views

**Comment by lpirl** [comment]
I'd be fine with letting the code in because the `PagesController` will have to display information (such as `EvidenceItem`s) soon and the `SearchController` will be needed soon as well.
If you feel that some parts should be explicitly marked as legacy, you can do so.

**Comment by klauszhang** [comment]
cool. all legacy solved, tags added in 96fe9d6f91e4b948e3e6579d4c5f1a0fc463e85c
this issues will be closed tomorrow if you guys all agree.

**Comment by klauszhang** [comment]
one more thing. I would say next time 
1. we just merge our own branch. or 
  this will have problem when more people are writing code.
2. we only push the-branch-need-to-be-merged onto github.
  then the functional branch just in local.

please leave your suggestion

**Comment by lpirl** [comment]
1. Yes. I just saw there was nothing more going on from your side (on GitHub) so I thought I can merge this. I should have asked you what to merge.
2. Not sure what "the functional branch" is, but yes: the relevant branch should be pushed (although I am not quite sure why an extra, local one is required).

**Comment by klauszhang** [comment]
the `functional branch` means `test branch or sort of things`. when we are testing new thoughts or gems. these stuff should be leave local **unless** they are asked to push.
i think this also stop things like careless mistake from happening.
