### ISSUE TITLE
Heroku failed

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#11]
I tried to push development to heroku and it failed. part of the log files are here (the failure part i think):
```
       Running: rake assets:precompile
       DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/build_d0caccdf3f69058747b0b5fd636f1611/Rakefile:7)
       DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/build_d0caccdf3f69058747b0b5fd636f1611/Rakefile:7)
       rake aborted!
```

**Comment by klauszhang** [comment]
remote:        PG::ConnectionBad: could not connect to server: Connection refused
remote:        Is the server running on host "127.0.0.1" and accepting
remote:        TCP/IP connections on port 5432?

a lot of error here..

remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !     Attempted to access a nonexistent database:
remote:  !     https://devcenter.heroku.com/articles/pre-provision-database
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...........
remote: 
remote: !	Push rejected to serlerhao.
remote:

**Comment by lpirl** [comment]
The deprecation warning is not causing the failure.
You just have to push the branch develop to GitHub (`origin`, so just a simple `git push`), it will be automatically deployed.
Did you push you local branch `develop` to GitHub? I could help you debugging this then.

**Comment by klauszhang** [comment]
yes i have pushed the most recent ready version here. but I think the warning is saying the gem is in vendor/plugins. they won't let us use it?

**Comment by klauszhang** [comment]
btw, how to push a develop branch to heroku with production settings and get it compiled? i pushed non-master branches it simply says it won't compile non-master branch.

**Comment by lpirl** [comment]
I just checked the deployment of the current `develop` and [it worked](https://sdm15serler-stream2-dev.herokuapp.com/).

You did not ask me for access rights to Heroku, so where did you get the log from? :)

The code pushed to `develop` on GitHub will be deployed automatically. Heroku will wait for Travis CI to succeed and then deploy everything (same is true for `master`).

The different settings are maintained though the rails environments `development`, `test`, and `production`.

**Comment by klauszhang** [comment]
~~obviously i hacked your computer~~  the truth is I registered a new heroku account and pushed my local code to it. : )
is it means when deployment fails we can get a prompt from CI? this is really a magic I need to learn about.
unfortunately the magic didn't happen. we have to change the search engine anyway.
there should be another issue about changing it.

**Comment by lpirl** [comment]
Ah then you probably have to add Postgres to your Heroku app and define the configuration variable `SECRET_TOKEN` in your Heroku app settings.

Not exactly. You can receive emails from Travis if the *build* fails (see links in the [Wiki page on CI](https://github.com/sdm15stream2/serler/wiki/Continuous-Integration)).
The deployment will only happen for builds that succeeded.

**Comment by klauszhang** [comment]
http://stackoverflow.com/questions/29306082/error-while-deploying-to-heroku-rake-assetsprecompile-pgconnectionbad-could

here is the solution. but there still some problems.

**Comment by lpirl** [comment]
This can only be true for your Heroku account, in the one linked to the README, Postgres is up and running.

**Comment by klauszhang** [comment]
fixed with replacing sunspot by ransack 
http://railscasts.com/episodes/370-ransack
https://github.com/activerecord-hackery/ransack
18394efc3232a56dec83f7b043021654ec16cd74

**Comment by lpirl** [comment]
Wow, thanks for setting this up!
