### ISSUE TITLE
ignore sunspot data

### ISSUE THREAD

**Issue by lpirl** [sdm15stream2/serler#12]
[According to this](http://stackoverflow.com/a/26314561) there is no  need to store all the sunspot data in the repository. I suggest removing and gitignoring it.
E.g. this paths:
<pre>
solr/data
solr/test
solr/development
solr/default/data
solr/pids
/log/*.log.lck
</pre>
(The less *data* in version control, the better)

**Comment by klauszhang** [comment]
great. but i think we can no longer use it in Heroku... have a try and you will get a `We're sorry, but something went wrong.` prompt.

**Comment by lpirl** [comment]
True… don't bother rearranging the chairs on the deck of the Titanic…

**Comment by klauszhang** [comment]
before we remove sunspot. can you have a test whether it is really NOT working on Heroku? I really don't know how. @lpirl

**Comment by lpirl** [comment]
done with 4900b251f94c021ef2389869bc9a46cfb6f28d55 - thanks @klauszhang

**Comment by klauszhang** [comment]
this gitignore have some problems.. I reindexed all stuff and pushed the branch again. I will reopen the issue after everything sorted.

**Comment by klauszhang** [comment]
i think it is because it ignored the pid file make. this 27db50f4b1b9a993e3099ea8b9b5dbdcc3dbbff1 hopefully solved the problem

**Comment by lpirl** [comment]
Re-indexing is something that must happen locally. Indices should not into Git. Is it set up that way now? :)

**Comment by lpirl** [comment]
In other words: Maybe we just missed the re-indexing and should add that to the Wiki?!

**Comment by klauszhang** [comment]
yes maybe I missed some parts, I will try to delete the "solr" folder and install it again with existing setting to see if it works.

**Comment by klauszhang** [comment]
ok. i will remove the solr data folder and update wiki. I think it works. Just some parts missing.

**Comment by klauszhang** [comment]
strange... it works again. I don't know what exactly the problem is. can you have a try if it can running.
after clone the repo run all stuff according to https://github.com/sdm15stream2/serler/wiki
it now works fine on my machine.

**Comment by lpirl** [comment]
Great! Thanks for investigating!
