### ISSUE TITLE
Fail to attach ransack

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#14]
well, there is a small issue I don't know how to solve and get trapped for a few days. do you guys know how to solve the " undefined method `evidence_items_path' " problem?
I think it is because lack some sorts of helper class definition?
i will push the branch and if you can help me with it.
see to this: ffb28a5ca1490e9b9b5d98c47bd26167e9d8f714

I believe I have seen the solution to this problem somewhere, maybe it is because the resource in route.rb? but I tried hard to google it and nothing is found. : (

Thank you.

**Comment by lpirl** [comment]
It seemed that ransack's `search_form_for` requires some URL helpers such as `evidence_items_path`.
We created a dummy URL for the resource EvidenceItems, what apparently fixed the issue.

**Comment by klauszhang** [comment]
fixed with 18394efc3232a56dec83f7b043021654ec16cd74
thanks Luksa!
