### ISSUE TITLE
add styling making the application more fancy.

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#15]
as required by PO, will do at the end of this sprint to improve product quality.

**Comment by lpirl** [comment]
Maybe we can put design guidelines in the Wiki (we probably won't write them ourselves but use nice ones that other people wrote and provided for re-use)?

**Comment by klauszhang** [comment]
basically we will stick to basic bootstrap style I think, I added saas in early stage to set variables (colors,fonts,size) so that we can use defined color in or design.
there are also some other options such as google material which looks rather fancy.
https://design.google.com/articles/

**Comment by klauszhang** [comment]
and this repo uses material which looks equally awesome. http://materializecss.com/
but, anyway. for simplify, personality I would prefer bootstrap.

**Comment by lpirl** [comment]
following Bootstrap guidelines sound good

**Comment by klauszhang** [comment]
yeah.. since it have already embedded in rails. anyway, all the frameworks are not too hard to implement.  I will try to create some demo some day within this week. or you have some idea, please share :smile:

**Comment by lpirl** [comment]
done, thanks to @shyamg91
