### ISSUE TITLE
refactor Search{Url,Result}

### ISSUE THREAD

**Issue by lpirl** [sdm15stream2/serler#17]
* rename `SearchUrl` to `SavedSearchQuery`
  * why `Saved…`: because it makes it clearer that this is not the current query, but a query saved by a user for later re-use
  * why `…Url` -> `…Query`: because saving the URL is how we implemented it but saving a query is the value for the user
* rename `SearchResult` to `SavedSearchResult`
  * why `Saved…`: because it makes it clearer that this is not the current result set, but a result set saved by a user for later re-use

**Comment by klauszhang** [comment]
ok. actually these two stuff should live inside the Search controller. but this will make current develop complicated. you can view this article and see the comment part if you are interested. I think we should not implement this in current project. (for simplicity :P)
 http://guides.rubyonrails.org/getting_started.html#adding-a-second-model

**Comment by klauszhang** [comment]
-.- why I can't assign two people to handle this...

**Comment by lpirl** [comment]
hold on :) please do not work on this - I'll have to touch a lot of files and we will have terrible merge conflicts. It's horribly hard, I'll do this.

**Comment by lpirl** [comment]
oh by the way: you are completely right, the `create` should for those two should live in the search controller and I'll move it there as well.

**Comment by klauszhang** [comment]
well, isn't it a lot of work for refactoring so many stuff? I don't think we need to do that (moving sth inside another) unless we are required. no user story about this.  even I think this should be a stand alone controller provided by the user team. or at least an interface provided.
I think you can just leave it as. unless we are asked to.
I am busy with rm experiment and software architecture paper.. maybe I can only commit after those finished.. they are ALL going do due!! x_x
Cheers.

**Comment by lpirl** [comment]
Never mind, it is not much work for me, I don't like to have code of questionable quality around ;)

**Comment by klauszhang** [comment]
well ok~ I was thinking this should be a requirement problem other than quality problem. My idea is to prepare for it instead of implement it. 
Anyway, it's ok if it don't take much of your time.

**Comment by lpirl** [comment]
Well, core quality is usually not part of the requirements. The PO does not care. Also, with our current approach it is very hard to display form errors etc.

**Comment by klauszhang** [comment]
Em.. ok! Sounds it should be like this.

**Comment by lpirl** [comment]
done in b5500e0
