### ISSUE TITLE
define CSS color variables

### ISSUE THREAD

**Issue by lpirl** [sdm15stream2/serler#19]
whatever seems reasonable, maybe:
* `bg1`
* `fg1`
* `bg2`
* `fg2`
* `bg3`
* `fg3`
* `notice`
* `warn`
* `error`

aligned with the colors from bootstrap!?
(Where `bg1` goes on top of `bg2` etc.)

**Comment by klauszhang** [comment]
I would use to
— for general purpose ---
color1,color2,color3…color5 
we can grab five different color from adobe color picker. where is really awesome.

and then: black, white (usually not so black and white, use eee for white and 222 for black. sometimes it is nicer.

then for notice board: promp, warn,  error

using bg and fg is good but you can just use lighten($color1, 30%) or darken($white, 40%) in compass I’ve added. which maybe can make more sense for me.

just some suggestions. I am fine with bg and fg. : )

**Comment by lpirl** [comment]
I don't care too much as long as it's not much to type and flexible. When using `lighten($color1, 30%)` we have to write that everywhere, have to remember that is is 30% and how to change this globally? I'd vote for simple variables but I am fine with whatever.

**Comment by klauszhang** [comment]
No, you only use lighten($color1, 30%) when need to. So that when you
change  $color1 that color will change too. That's the idea. You can create
a unlimited set of color of same hue but different lightness. But anyway,
it really isn't important in such a small project. I am ok with anything.:)

**Comment by lpirl** [comment]
I got that, thanks - but what if I want to change 30% globally? ;)

**Comment by klauszhang** [comment]
Just define $color1:lighten($oldcolor1,30%)

**Comment by lpirl** [comment]
I see it is hard to express that point. I'll try again:
Say we use `$maincolor`.
Then, we put `darken($maincolor,30%)` everywhere in the stylesheets where we use floating boxes for example.
Even if we define `$maincolor = darken($oldmaincolor, 30%)` the floating boxes will still have 30% "distance" to the new `$maincolor`.
Still, it is not so important.

**Comment by klauszhang** [comment]
well, sorry. we can't use a mixin in the variable define section. such as `$color1:lighten(#ccc,10%)` so if we are going to change `$color1` and make it lighter globally, we can only do like this $color1:#ddd; 
anyway, its just some labor, done by human.
however, when we are using some darker color in context. such as:
```html
<div class='lighter'> this is lighter</div>
```
then we can do like this
```css
$color1:#112233; //defined in global variable
.lighter{
background-color:lighten($color1,30%)
}
```

so if we change `color1:#223344` the `.lighter` class will also be affected.
here is a demo.  http://jackiebalzer.com/color you change base color only. other color you can use function to calculate. so we only need to manage 5 color + 2 black and white.

**Comment by klauszhang** [comment]
btw, If we are going to change the color in bootstrap. it will be a little bit of complicated. we need to include the bootstrap sass file and configure its variable. it is not very hard. but I don't think it is necessary.

the reason of using sass and compass is:
* use nested code in css, such as:
```css
main{
   .highlight{
      color:red;
   }
}
```
* use mixins, such as the lighten we have talked about:
```css
// in _variable.css.scss
$color1:#123;
```
```css
//actual place
@import 'variable';
body{
   background-color: darken($color1,30%);
}
```
* use module to manage massive css code, just like the previouse `@import 'variable'` we can write:
```css
@import 'variable';
@import 'layout';
@import 'header';
@import 'main';
//etc..
```
then different code can live in different files. and they can nested. easy to manage.

**But this doesn't means we have to use them...because this project is small and style seems not so essential, so I think stick to whatever you prefer, I will be fine with them.**

if you are interested, you can refer to: [compass] (http://compass-style.org/) and [sass] (http://sass-lang.com/)

**Comment by shyamg91** [comment]
Alright guys just saw this. I've taken liberty to assign names to color variables

**Comment by lpirl** [comment]
All good.

**Comment by shyamg91** [comment]
Since i've worked with sass, i don't see any scope of having to use mixins just yet cause we haven't used too much of box shading.

**Comment by klauszhang** [comment]
lovely~ you’re the style master :)

**Comment by lpirl** [comment]
Obsolete. Adequately done by @shyamg91 . Thanks.
