### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by lpirl** [sdm15stream2/serler#2]
Travis or what you like…

**Comment by lpirl** [comment]
I set up the branch `delta-setup_ci` for this.

**Comment by lpirl** [comment]
Done.
Still needs rspec (prepared) and cucumber(?) integration.

**Comment by klauszhang** [comment]
amazing! can you give us more info about the stuff you have done in our next meet-up? I really interesting how these CI works.

**Comment by lpirl** [comment]
It's just creating [this file](https://github.com/sdm15stream2/serler/blob/master/.travis.yml), logging in into Travis and allow access to your repository.
