### ISSUE TITLE
cucumber test must be changed before we can deploy advanced search into ci

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#24]
When I fill in "Search for:" with "saasbook" 

there is no such kind of stuff now...I will do a unit test after I finish the adv search part. testers please help me fix this problem. ; )

**Comment by klauszhang** [comment]
the search is done by d8fa22c9cb671a30d4ce96e94be9494797474aec . please update the test to get rid of the ci error?

**Comment by bakhshb** [comment]
Hi Developers,


I can not  locate the selectors, so I do not know how to test them.. this is so complicated 




regards

Baraa


Sent from Windows Mail





From: Hao Zhang
Sent: ‎Thursday‎, ‎8‎ ‎October‎ ‎2015 ‎2‎:‎20‎ ‎p.m.
To: sdm15stream2/serler





the search is done by d8fa22c . please update the test to get rid of the ci error?

**Comment by lpirl** [comment]
Baraa,

did you see this?

http://stackoverflow.com/questions/20134085/how-to-select-option-in-drop-down-using-capybara

Lukas

On 10/08/2015 03:58 PM, bakhshb wrote:
> Hi Developers,
>
>
> I can not locate the selectors, so I do not know how to test them.. this
> is so complicated
>
>
>
>
> regards
>
> Baraa
>
>
> Sent from Windows Mail
>
>
>
>
>
> From: Hao Zhang
> Sent: ‎Thursday‎, ‎8‎ ‎October‎ ‎2015 ‎2‎:‎20‎ ‎p.m.
> To: sdm15stream2/serler
>
>
>
>
>
> the search is done by d8fa22c . please update the test to get rid of the
> ci error?
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdm15stream2/serler/issues/24#issuecomment-146403971>.
>

-- 
+49 174 940 74 71
+64 21 150 86 86
GPG: http://lukas-pirl.de/media/attachments/lukas_pirl.pub

**Comment by bakhshb** [comment]
Developers,


Oh, I was trying to look for data in empty field that why I had an error.


Can you please tell me why methodology and methods are empty?


 




regards

Baraa


Sent from Windows Mail





From: Lukas Pirl
Sent: ‎Thursday‎, ‎8‎ ‎October‎ ‎2015 ‎4‎:‎49‎ ‎p.m.
To: sdm15stream2/serler
Cc: bakhshb




Baraa,

did you see this?

http://stackoverflow.com/questions/20134085/how-to-select-option-in-drop-down-using-capybara

Lukas

On 10/08/2015 03:58 PM, bakhshb wrote:
> Hi Developers,
>
>
> I can not locate the selectors, so I do not know how to test them.. this
> is so complicated
>
>
>
>
> regards
>
> Baraa
>
>
> Sent from Windows Mail
>
>
>
>
>
> From: Hao Zhang
> Sent: ‎Thursday‎, ‎8‎ ‎October‎ ‎2015 ‎2‎:‎20‎ ‎p.m.
> To: sdm15stream2/serler
>
>
>
>
>
> the search is done by d8fa22c . please update the test to get rid of the
> ci error?
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdm15stream2/serler/issues/24#issuecomment-146403971>.
>

-- 
+49 174 940 74 71
+64 21 150 86 86
GPG: http://lukas-pirl.de/media/attachments/lukas_pirl.pub

**Comment by klauszhang** [comment]
Hi Baraa
did you do
rake db:migrate
rake db:fixtures:load
?

if you did, please post the error message. or delete the database by `rake db:drop` and start over again.

Regards,
HZ

**Comment by bakhshb** [comment]
yes that works 


thanks Hao


regards 

Baraa






Sent from Windows Mail





From: Hao Zhang
Sent: ‎Thursday‎, ‎8‎ ‎October‎ ‎2015 ‎5‎:‎43‎ ‎p.m.
To: sdm15stream2/serler
Cc: bakhshb




Hi Baraa
did you do
rake db:migrate
rake db:fixtures:load
?

if you did, please post the error message. or delete the database by `rake db:drop` and start over again.

Regards,
HZ

**Comment by klauszhang** [comment]
Done, Thanks Baraa
