### ISSUE TITLE
setup deployment

### ISSUE THREAD

**Issue by lpirl** [sdm15stream2/serler#3]
To Heroku or what you like…

**Comment by buddalasunil999** [comment]
both are new for me. which is best?

**Comment by lpirl** [comment]
I think the book features a chapter on how to deploy to Heroku and most of the students probably did this already so maybe we just stick with Heroku…

**Comment by buddalasunil999** [comment]
ok. But do we get all what we need out of Heroku for continuous delivery? Or do you see any advantage with Travis?

**Comment by lpirl** [comment]
Those are two completely different services (and therefore in different tickets). You may want to read up again what they are there for.

**Comment by buddalasunil999** [comment]
Oh ok, I thought Heroku also provides CI. But not. Then we need to combine Travis CI and Heroku. Build with Travis and deploy to Heroku. What say?

**Comment by buddalasunil999** [comment]
Oh ok. I thought Heroku provides Continuous Integration as well. Then we can use Heroku and Travis CI.

**Comment by lpirl** [comment]
That is what I thought :)

**Comment by lpirl** [comment]
[done](https://sdm15serler-stream2.herokuapp.com/)
