### ISSUE TITLE
Sunspot Readme

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#6]
Source: http://sunspot.github.io/sunspot/docs/
I am adding useful stuff into this thread to know how to use the search engine - Hao
## Setup

It already in Gemfiles
```ruby
gem 'sunspot_rails'
gem 'sunspot_solr' # optional pre-packaged Solr distribution for use in development
```
Bundle it!
```ruby
bundle install
```
Generate a default configuration file:
```ruby
rails generate sunspot_rails:install
```
If sunspot_solr was installed, start the packaged Solr distribution with:
`bundle exec rake sunspot:solr:start #` or `sunspot:solr:run to start in foreground`

## Setup objects
Add a searchable block to the objects you wish to index.
```ruby
class Post < ActiveRecord::Base
  searchable do
    text :title, :body
    text :comments do
      comments.map { |comment| comment.body }
    end

    boolean :featured
    integer :blog_id
    integer :author_id
    integer :category_ids, :multiple => true
    double  :average_rating
    time    :published_at
    time    :expired_at

    string  :sort_title do
      title.downcase.gsub(/^(an?|the)/, '')
    end
  end
end
```
text fields will be full-text searchable. Other fields (e.g., integer and string) can be used to scope queries.

TODO: add search item in controllers.

**Comment by lpirl** [comment]
Thanks for figuring that out!
If you just copy stuff from somewhere else, I'd suggest including links into the README.
The issues more correspond to things that are to be done eventually.
Would you mind doing so and closing this issue afterwards?

**Comment by klauszhang** [comment]
Sure, will do.
