### ISSUE TITLE
Git for GUI users

### ISSUE THREAD

**Issue by klauszhang** [sdm15stream2/serler#9]
I will provide git suggestions for gui users in wiki. If you wish.

using gui will make things easier. you can use command line if you wish.

**Comment by klauszhang** [comment]
... how many people is interesting about this issue? if i am the only one interesting, this make no sense for me to do this.. : )

**Comment by lpirl** [comment]
I prefer the CLI

**Comment by klauszhang** [comment]
so there is no sense to make this : )
